Resources:
  AuroraCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-postgresql
      EngineVersion: "15.3"
      DatabaseName: mydb
      MasterUsername: tunderahman
      MasterUserPassword: Tunde123!#Tunde123!#
      ServerlessV2ScalingConfiguration:
        MinCapacity: 0.5
        MaxCapacity: 4


  AuroraInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBClusterIdentifier: !Ref AuroraCluster
      DBInstanceClass: db.serverless
      Engine: aurora-postgresql
